language: python
python:
  - "2.7"
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install pytest-cov
# command to run tests
script: pytest --cov bootstrap
after_success:
    - coveralls
